---
language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - ree
  - ruby-head
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: 1.8.7
      jdk: oraclejdk7
    - rvm: 1.8.7
      jdk: openjdk6
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: oraclejdk7
    - rvm: rbx-19mode
      jdk: openjdk6
    - rvm: rbx-18mode
      jdk: openjdk7
    - rvm: rbx-18mode
      jdk: oraclejdk7
    - rvm: rbx-18mode
      jdk: openjdk6
    - rvm: ree
      jdk: openjdk7
    - rvm: ree
      jdk: oraclejdk7
    - rvm: ree
      jdk: openjdk6

