aws:
  access_key: AWS_ACCESS_KEY
  secret: AWS_SECRET
  bucket_name: BUCKET_NAME
backup:
  dir_base: PATH_TO_BACKUP_DIRECTORY
  file_name_base: SOME_BASE_NAME
  backups_to_keep:
    remote: 2
    local: 5
jenkins:
  home: PATH_TO_JENKINS_HOME
verbose: true
